Repository senseteq-io/dent-in-patient, pull requests merged in 2022-07, with the labels that each got.

#4 Bugfix swe 643 fix vipps multiple calling
  .env.development
  .env.production
  src/__constants__/authProviders.js
  src/domains/Booking/components/BookingSimpleView/BookingSimpleView.js
  src/domains/Session/components/SetNewPasswordForm/SetNewPasswordForm.js
  src/domains/Session/helpers/index.js
  src/domains/Session/helpers/transformUserDataFromVipps.js
  src/domains/Session/hooks/index.js
  src/domains/Session/hooks/useSessionActions/actions/completeNewPassword.js
  src/domains/Session/hooks/useVippsAuth/index.js
  src/domains/Session/hooks/useVippsAuth/useVippsAuth.js
  src/domains/Session/hooks/useVippsFlowBackgroundActions/index.js
  src/domains/Session/hooks/useVippsFlowBackgroundActions/useVippsFlowBackgroundActions.js
  src/domains/User/components/UserSimpleForm/UserSimpleForm.js
  src/domains/User/context/UserProvider.js
  src/hooks/index.js
  src/hooks/useTransformRoutesRedirectProperties.js
  src/hooks/useVippsLogin.js
  src/pages/Auth/VippsCallback.js
  src/pages/RoutesRedirect.js
  src/utils/index.js
  src/utils/sendBackendRequest.js
Labels: bug

#7 Bugfix swe 1226 set new password page displaying
  src/components/BoilerplateLayout/BoilerplateLayout.js
  src/components/BoilerplateLayout/components/AccountMenu/AccountMenu.js
  src/domains/Session/components/LoginForm/LoginForm.js
  src/domains/Session/hooks/useSessionActions/actions/login.js
  src/hooks/useTransformRoutesRedirectProperties.js
  src/pages/RoutesRedirect.js
Labels: visual, bugfix, logic

#8 [FEATURE][SWE-1128]add translation module
  .env.development
  .env.production
  .gitignore
  package-lock.json
  package.json
  src/contexts/Translation/TranslationsContext.js
  src/contexts/Translation/TranslationsProvider.js
  src/contexts/Translation/__constants__/index.js
  src/contexts/Translation/useTranslations.js
  src/domains/Booking/components/BookingSimpleView/BookingSimpleView.js
  src/index.js
  src/pages/App/Booking/BookingsAll.js
  yarn.lock
Labels: feature

#10 [FEATURE][SWE-1552][override useCollection and booking show componets]
  src/__constants__/bookingsFetchLimit.js
  src/__constants__/index.js
  src/__constants__/statuses.js
  src/__constants__/time.js
  src/domains/Booking/__constants__/bookinsCounters.js
  src/domains/Booking/components/BookingList/BookingList.js
  src/domains/Booking/components/BookingsByType/BookingsByType.js
  src/domains/Booking/components/BookingsByType/index.js
  src/domains/Booking/components/index.js
  src/domains/Booking/hooks/get/index.js
  src/domains/Booking/hooks/get/useBookings.js
  src/domains/Booking/hooks/get/useGetBookings/index.js
  src/domains/Booking/hooks/get/useGetBookings/useGetBookings.js
  src/domains/Booking/hooks/get/useGetBookingsCounter.js
  src/hooks/useCollection.js
  src/pages/App/Booking/BookingsAll.js
  src/styles/vars.css
Labels: feature
